version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:45"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stripe
    versions:
    - 8.132.0
    - 8.133.0
    - 8.134.0
    - 8.135.0
    - 8.136.0
    - 8.137.0
    - 8.138.0
    - 8.139.0
    - 8.140.0
    - 8.141.0
    - 8.142.0
    - 8.143.0
    - 8.145.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 3.9.9
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: bn.js
    versions:
    - 5.1.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
  rebase-strategy: disabled
  registries:
  - npm-registry-registry-npmjs-org
